

export const LOADING = 'LOADING';

export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SET_CURRENT_USER = 'AUTH_SET_CURRENT_USER';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const DASHBOARD_CREATE = 'DASHBOARD_CREATE';
export const DASHBOARD_EDIT = 'DASHBOARD_EDIT';
export const DASHBOARD_DELETE = 'DASHBOARD_DELETE';
export const USER_DATA = 'USER_DATA'
